<a href="https://colab.research.google.com/github/MarcosRolando/OrgaDeDatosTP2/blob/main/neuralNetwoork_agus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q -U keras-tuner
import kerastuner as kt
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import math as mt
from tensorflow import feature_column

In [2]:
df = pd.read_csv('/content/Train_TP2_Datos_2020-2C.csv')
df.drop_duplicates('Opportunity_ID', inplace=True)
df = df[(df['Brand'] == 'None') & (df['Sales_Contract_No'] == 'None')]
df = df[df['Stage'] == 'Closed Won']
df.head(20)

         ID    Region  ...       Stage       Prod_Category_A
7     27455  Americas  ...  Closed Won  Prod_Category_A_None
63    13392      EMEA  ...  Closed Won  Prod_Category_A_None
64    19342  Americas  ...  Closed Won  Prod_Category_A_None
65    24444     Japan  ...  Closed Won  Prod_Category_A_None
66    18491      EMEA  ...  Closed Won  Prod_Category_A_None
67    18494      EMEA  ...  Closed Won  Prod_Category_A_None
70    19680      EMEA  ...  Closed Won  Prod_Category_A_None
73    16829      EMEA  ...  Closed Won  Prod_Category_A_None
79    18279      EMEA  ...  Closed Won  Prod_Category_A_None
139   23618     Japan  ...  Closed Won  Prod_Category_A_None
140   23619     Japan  ...  Closed Won  Prod_Category_A_None
142   23617     Japan  ...  Closed Won  Prod_Category_A_None
182   23923      EMEA  ...  Closed Won  Prod_Category_A_None
183   19174      EMEA  ...  Closed Won  Prod_Category_A_None
184   19178      EMEA  ...  Closed Won  Prod_Category_A_None
194   19135     Japan  ...  Closed Won  Prod_Category_A_None
195   19138     Japan  ...  Closed Won  Prod_Category_A_None
4040  28613     Japan  ...  Closed Won  Prod_Category_A_None
4130  28611     Japan  ...  Closed Won  Prod_Category_A_None
4284  23260      EMEA  ...  Closed Won  Prod_Category_A_None

[20 rows x 52 columns]

Tuneamos algunas cosas del DataFrame que notamos en el analisis de los datos.

In [3]:
def preprocess_dataframe(df):

  df.fillna(value=0, inplace=True) #Reemplazamos NAN por 0, ya que NAN rompe a Tensorflow

  #Renombramos las columnas que tienen caracteres que TensorFlow no acepta como validos.
  #Estos particularmente son whitespace, coma y parentesis por ejemplo.
  df.rename(columns={'ASP_(converted)':'ASP_converted','Pricing, Delivery_Terms_Quote_Appr':
                    'Pricing_Delivery_Terms_Quote_Appr','Pricing, Delivery_Terms_Approved':
                    'Pricing_Delivery_Terms_Approved','Source ':'Source'},inplace=True)

  df = df[df['Stage'].isin(['Closed Won', 'Closed Lost'])]
  df.loc[:, 'Stage'].replace({'Closed Won':1, 'Closed Lost':0}, inplace=True) #0 corresponde a que el caso fue Closed Lost, 1 a que fue Closed Won. Asi tenemos un problema de clasificacion binario que puede entender la red neuronal.

  df.loc[:, 'Planned_Delivery_Start_Date'] = pd.to_datetime(df['Planned_Delivery_Start_Date'], 'coerce',
                                                                  format='%m/%d/%Y')
  df.loc[:, 'Planned_Delivery_End_Date'] = pd.to_datetime(df['Planned_Delivery_End_Date'], 'coerce',
                                                                                      format='%m/%d/%Y')
  df = df[df['Opportunity_ID'] != 9773] #Hardcodeo este filtrado porque el id 9773 tiene mal cargada la fecha de delivery end, dando una diferencia de 200 anios xd"

  #Pongo .loc porque pandas me jode con warnings que son falsos positivos de slice copy"
  #Gracias Pandas!"

  #Creamos una nueva columna (Feature Engineering) que contiene la longitud en dias 
  #estimada de la operacion. En el informe habiamos encontrado que aparentaba haber
  #una relacion cuadratica de decrecimiento a medida que aumentaban los dias donde disminuia
  #la chance de completar la operacion.
  df['Delta_Time'] = df['Planned_Delivery_End_Date'] - df['Planned_Delivery_Start_Date']
  df.loc[:, 'Delta_Time'] = df['Delta_Time'].dt.days
  df['Delta_Time'] = df.groupby('Opportunity_ID')['Delta_Time'].transform('max')

  #Pasamos todo a dolares
  currency_conversion = {'AUD':0.707612, 'EUR':1.131064, 'GBP':1.318055, 'JPY':0.008987, 'USD':1.0}
  df['Total_Taxable_Amount_Currency'] = df[['Total_Taxable_Amount_Currency']].replace(currency_conversion)
  df['Total_Taxable_Amount'] = df['Total_Taxable_Amount_Currency'] * df['Total_Taxable_Amount']

  #Modifico la columna Brand para que en vez de decir que marca es, solo diga
  #si tiene o no marca. Es importante aclarar que verificamos que siempre que una oportunidad
  #tiene un producto con marca entonces todos sus productos tienen marca. Esto se cumple
  #tanto en el set de entrenamiento como en el de test, por lo tanto al hacer drop_duplicates
  #no nos va a pasar nunca el caso donde nos pudieramos quedar con una entrada de producto
  #sin marca mientras que algun otro producto si tuviera, ya que confirmamos que o todos tienen
  #marca o ninguno tiene.
  df.loc[df['Brand'] == 'None', 'Brand'] = 'No'
  df.loc[df['Brand'] != 'No', 'Brand'] = 'Yes'

  #Agrego una columna que indica si tiene o no numero de contrato
  df.loc[:, 'Sales_Contract_No'][df['Sales_Contract_No'] != 'None'] = 'Yes'
  df.loc[:, 'Sales_Contract_No'][df['Sales_Contract_No'] == 'None'] = 'No'
  df.rename(columns={'Sales_Contract_No':'Has_Contract_Number'}, inplace=True)

  #Agrego una columna que indique la cantidad de productos que tiene esa
  #oportunidad
  df['Product_Name'] = 1
  df['Product_Amount'] = df.groupby('Opportunity_ID')['Product_Name'].transform(lambda x: x.sum())

  #Agrego una columna que indica si el owner de la cuenta es el mismo que el de la oportunidad
  #o no
  df['Same_Owner'] = (df['Account_Owner'] == df['Opportunity_Owner'])
  df['Same_Owner'] = df['Same_Owner'].replace({False:'No', True:'Yes'})


  #Reemplazo las 4 columnas de aprobacion por solo 2 columnas que indiquen si tuvo la aprobacion
  #de delivery y burocratica o no. Recalco que si nunca la necesito seria equivalente a si
  #la necesito y la consiguio.
  df['Delivery_Approved'] = df['Pricing_Delivery_Terms_Quote_Appr'] + df['Pricing_Delivery_Terms_Approved']
  df['Delivery_Approved'] = df['Delivery_Approved'].replace({0:1, 1:0, 2:1})
  df['Bureaucratic_Code_Approved'] = df['Bureaucratic_Code_0_Approval'] + df['Bureaucratic_Code_0_Approved']
  df['Bureaucratic_Code_Approved'] = df['Bureaucratic_Code_Approved'].replace({0:1, 1:0, 2:1})

  #Cambio TRF por una columna que es el valor medio de los TRF de la oportunidad
  df["TRF"] = df.groupby("Opportunity_ID")["TRF"].transform("mean")

  #Pruebo volar duplicados, solo cambia el producto. Si el producto no importa
  #entonces volar duplicados no deberia importar. Obviamente vuelo el producto en el que
  #quede tambien.
  df.drop_duplicates('Opportunity_Name',inplace=True)
  df.drop(columns=['Product_Name','Product_Family','Opportunity_Name'],inplace=True)

  #Normalizo las columnas numericas
  normalized_columns = ['ASP_converted','TRF','Total_Taxable_Amount', 'Product_Amount']
  for column in normalized_columns:
    df[column] = (df[column] - df[column].mean()) / df[column].std()

  #Borro columnas que tengan el mismo dato en todas las entradas, o inconsecuentes como el ID / Opportunity_ID
  #Algunas columnas borradas son porque pienso que no tienen incidencia, ir viendo.
  #TODO: Analizar si el Sales_Contract_No no es que importe el numero en si, sino si tiene
  #o no tiene numero de contrato. Por ahora no lo meto como input.
  #TODO: Ver el mismo tema con la columna 'Price', la mayoria tiene None u Other
  #y solo unos pocos tienen precio numerico. Quiza importe que tenga precio o no tenga,
  #o si no tiene precio quiza importe si es None u Other. Por ahora no lo pongo
  #como input.
  df.drop(columns=['Submitted_for_Approval', 'Last_Activity', 'ASP_(converted)_Currency', 
                  'Prod_Category_A', 'ID', 'Opportunity_ID'],inplace=True)

  #Drop columnas que quiza podamos usar pero por ahora no las uso
  df.drop(columns=['Account_Created_Date','Opportunity_Created_Date',
                  'Quote_Expiry_Date','Last_Modified_Date',
                  'Planned_Delivery_Start_Date','Planned_Delivery_End_Date',
                  'Month','Delivery_Quarter', 'Delivery_Year', 'Actual_Delivery_Date',
                  'Price','ASP','ASP_Currency','Total_Amount_Currency',
                  'Total_Amount','Total_Taxable_Amount_Currency','Currency',
                   'Product_Category_B','Last_Modified_By', 'Account_Owner',
                   'Opportunity_Owner','Account_Name','Product_Type','Size',
                   'Territory', 'Billing_Country', 'Pricing_Delivery_Terms_Quote_Appr',
                   'Pricing_Delivery_Terms_Approved', 'Bureaucratic_Code_0_Approval',
                   'Bureaucratic_Code_0_Approved'],
                   inplace=True)

  #Definimos que tipo de feature es cada columna

  #Debemos separar algunos de los registros para armar un set de test propio (no el de la catedra). De esta forma sabremos rapidamente
  #si nuestro modelo esta dando resultados optimos o no sin necesidad de estar subiendo el TP a Kaggle constantemente.
  #Sin embargo, no queremos usar tantos registros ya que estariamos disminuyendo el set de entrenamiento considerablemente.
  #Podemos empezar reservando 2000 registros para el test de prueba y ver que onda. Pasariamos de tener 16 mil a 14 mil 
  #registros para el set de entrenamiento, no es una perdida importantisima creo en principio, asi que arrancamos con eso.

  #Por otro lado, nuestro test de prueba deberia tener un 50 50 de Closed Won y Closed Lost, por lo que no podemos elegir asi nomas
  #al azar.

  return df

In [4]:
# Metodo que pasa de DataFrame de Pandas a un DataSet de TensorFlow
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('Stage') #Retorna la columna Stage, eliminandolo simultaneamente del DataFrame. 'Stage' seria nuestra columna 'target', es decir, lo que queremos predecir.
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels)) #Crea un DataSet cuyos elementos son slices de los tensores pasados a la funcion. Ver documentacion oficial para comprender bien.
  #En pocas palabras, le pasamos las columnas con los datos como diccionario (estilo 'columna':[dato1,dato2,dato3]) y una lista con los resultados estilo [resu1,resu2,resu3].
  #Se genera un DataSet del estilo [('columna':[dato1,dato2,dato3], [resu1, resu2, resu3])].
  #En realidad 'columna' es una lista de todas las columnas con sus correspondientes datos, pero se entiende la idea creo.
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe)) #Al tener el buffer_size del mismo tamanio que la cantidad de datos del dataset, tenemos perfect shuffling (ver documentacion para comprender).
    #Basicamente mezlcamos el dataset para que luego los batches que se armen contengan distintos elementos si lo entrenamos distintas veces.
  ds = ds.batch(batch_size) #Arma batches de tamanio batch_size entre elementos consecutivos del DataSet.
  return ds

In [5]:
#Arma las features, asignando las columnas del DataFrame segun corresponda al tipo de feature
#(numerico, categorico, etc). Entiendase por feature a las columnas del DataFrame.
def set_up_feature_columns(dataframe, numeric_columns, indicator_columns, bucket_columns, crossed_columns):
  features = []

  #numeric features
  for column_name in numeric_columns:
    features.append(feature_column.numeric_column(column_name))

  #bucket features
  boundaries = [] #En principio este boundary es solo para la columna 'Delta Time'. Ver de como generalizar.
  for i in range(38):
    boundaries.append(i*5.0)

  for column_name in bucket_columns:
    range_column = feature_column.numeric_column(column_name)
    bukect_column = feature_column.bucketized_column(range_column, boundaries)
    features.append(bukect_column)

  #indicator features (one-hot value vector, para aquellas columnas categoricas de pocas opciones)
  for column_name in indicator_columns:
    categorical_column = feature_column.categorical_column_with_vocabulary_list(
                                          column_name, dataframe[column_name].unique())
    indicator_column = feature_column.indicator_column(categorical_column)
    features.append(indicator_column)

  #crossed features
  for crossed_feature in crossed_columns:
    categorical_columns = []
    possible_values = 1
    for column_name in crossed_feature:
      column_keys = dataframe[column_name].unique()
      possible_values = possible_values * len(column_keys)
      categorical_columns.append(feature_column.categorical_column_with_vocabulary_list(
                                            column_name, column_keys))
    crossed_feature = feature_column.crossed_column(categorical_columns, hash_bucket_size=possible_values) #Ponemos la cantidad de buckets justos para representar todas las combinaciones
    features.append(feature_column.indicator_column(crossed_feature))

  return features

Preparamos los features para el modelo, es decir, seteamos cada una de las columnas que vayamos a utilizar del DataFrame. Luego generamos el DataSet en base al DataFrame para darselo como input al modelo.

In [12]:
  #Columnas que consideramos numericas
  numeric_columns = ['ASP_converted','TRF','Total_Taxable_Amount','Product_Amount']

  #Columnas que consideramos clasificatorias con rango numerico
  bucket_columns = ['Delta_Time']

  #Columnas que consideramos categoricas de pocos valores posibles
  indicator_columns = ['Region', 'Bureaucratic_Code','Source', 'Same_Owner',
                        'Account_Type',
                        'Opportunity_Type','Quote_Type','Delivery_Terms']
                        #'Product_Category_B','Last_Modified_By'
                        #'Product_Family', 'Product_Name', 'Opportunity_Name'
                        #'Account_Owner', 'Opportunity_Owner', 'Account_Name'
                        #'Product_Type','Size', 'Territory', 'Billing_Country'

  #Columnas crossed, aquellas que queremos un parametro por combinacion
  crossed_columns = [['Delivery_Approved','Bureaucratic_Code_Approved'],
                     ['Brand','Has_Contract_Number']]

  df = pd.read_csv('/content/Train_TP2_Datos_2020-2C.csv')
  df = preprocess_dataframe(df)

  features = set_up_feature_columns(df,numeric_columns,indicator_columns,bucket_columns, crossed_columns)

  #Separamos el DataFrame en uno de pruebo y el de entrenamiento. TODO: Ver el de validacion
  test_lines = 200

  np.random.seed(1)
  drop_indices = np.random.choice(df.index, test_lines, replace=False)
  df_test = df.loc[drop_indices, :]
  df.drop(drop_indices, inplace=True)

  #df_validation = df.tail(200)
  #df.drop(df.tail(200).index, inplace=True)

  feature_layer = tf.keras.layers.DenseFeatures(features)
  ds = df_to_dataset(df,batch_size=56, shuffle=True)
  ds_test = df_to_dataset(df_test, batch_size=56, shuffle=False)
  #ds_validation = df_to_dataset(df_validation, batch_size=56, shuffle=False)
  df

/usr/local/lib/python3.6/dist-packages/pandas/core/series.py:4582: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

         Region  ... Bureaucratic_Code_Approved
0          EMEA  ...                          1
1          EMEA  ...                          1
2      Americas  ...                          1
3      Americas  ...                          0
4      Americas  ...                          0
...         ...  ...                        ...
16939      EMEA  ...                          1
16940  Americas  ...                          1
16942      EMEA  ...                          1
16945  Americas  ...                          1
16946  Americas  ...                          1

[9590 rows x 18 columns]

In [ ]:
#ACA SE ESCRIBE EL TUNEO DE HIPERPARAMETROS

def model_builder(hyper_parameters):
  input_layer = feature_layer
  model = tf.keras.Sequential()
  model.add(input_layer)
  hidden_layers_amount = hyper_parameters.Int('hidden_layers_amount', min_value = 0, max_value = 2, step = 1)
  for i in range(hidden_layers_amount):
    model.add(tf.keras.layers.Dense(hyper_parameters.Int('hidden_layer_' + str(i), min_value = 1, max_value = 16, step = 1),\
                                    activation = hyper_parameters.Choice('activation_func', values = ["relu", "tanh", "sigmoid"])))
    #Podemos ver si hay mas funciones de activacion que valgan la pena
  model.add(tf.keras.layers.Dense(1, activation = "sigmoid"))
  learning_rate = hyper_parameters.Float('learning_rate', min_value=1e-5, max_value=1e-2, sampling='LOG')
  model.compile(optimizer = keras.optimizers.Adam(learning_rate = learning_rate,\ #Ver si hay otras cosas del optimizer para cambiar
                                                  loss = tf.keras.losses.BinaryCrossentropy(),\
                                                  metrics = ["accuracy"])
  
 tuner = kt.Hyperband(model_builder, objective = 'val_accuracy', max_epochs = 10, factor = 3,
                     directory = 'my_dir', project_name = 'intro_to_kt')

Creamos y compilamos el modelo. En esta seccion se tunean las propiedades del modelo.

In [7]:
model = tf.keras.Sequential([
  feature_layer,
  tf.keras.layers.Dense(1, activation='sigmoid')
])

In [8]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=['accuracy'])

Entrenamos el modelo

In [9]:
#Ignoren el WARNING, esta en la documentacion tambien. Nadie le da bola en StackOverflow xd.
#model.fit(ds, validation_data=ds_validation, epochs=60)
model.fit(ds, epochs=60)
model.summary()

Epoch 1/60
WARNING:tensorflow:Layers in a Sequential model should only have a single input tensor, but we receive a <class 'dict'> input: {'Region': <tf.Tensor 'ExpandDims_12:0' shape=(None, 1) dtype=string>, 'Bureaucratic_Code': <tf.Tensor 'ExpandDims_3:0' shape=(None, 1) dtype=string>, 'Source': <tf.Tensor 'ExpandDims_14:0' shape=(None, 1) dtype=string>, 'Has_Contract_Number': <tf.Tensor 'ExpandDims_8:0' shape=(None, 1) dtype=string>, 'Account_Type': <tf.Tensor 'ExpandDims_1:0' shape=(None, 1) dtype=string>, 'Opportunity_Type': <tf.Tensor 'ExpandDims_9:0' shape=(None, 1) dtype=string>, 'Quote_Type': <tf.Tensor 'ExpandDims_11:0' shape=(None, 1) dtype=string>, 'Delivery_Terms': <tf.Tensor 'ExpandDims_6:0' shape=(None, 1) dtype=string>, 'Brand': <tf.Tensor 'ExpandDims_2:0' shape=(None, 1) dtype=string>, 'ASP_converted': <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=float64>, 'TRF': <tf.Tensor 'ExpandDims_15:0' shape=(None, 1) dtype=float64>, 'Total_Taxable_Amount': <tf.Tensor 'ExpandDims_16:0' shape=(None, 1) dtype=float64>, 'Delta_Time': <tf.Tensor 'ExpandDims_7:0' shape=(None, 1) dtype=float64>, 'Product_Amount': <tf.Tensor 'ExpandDims_10:0' shape=(None, 1) dtype=float64>, 'Same_Owner': <tf.Tensor 'ExpandDims_13:0' shape=(None, 1) dtype=string>, 'Delivery_Approved': <tf.Tensor 'ExpandDims_5:0' shape=(None, 1) dtype=int64>, 'Bureaucratic_Code_Approved': <tf.Tensor 'ExpandDims_4:0' shape=(None, 1) dtype=int64>}
Consider rewriting this model with the Functional API.
WARNING:tensorflow:Layers in a Sequential model should only have a single input tensor, but we receive a <class 'dict'> input: {'Region': <tf.Tensor 'ExpandDims_12:0' shape=(None, 1) dtype=string>, 'Bureaucratic_Code': <tf.Tensor 'ExpandDims_3:0' shape=(None, 1) dtype=string>, 'Source': <tf.Tensor 'ExpandDims_14:0' shape=(None, 1) dtype=string>, 'Has_Contract_Number': <tf.Tensor 'ExpandDims_8:0' shape=(None, 1) dtype=string>, 'Account_Type': <tf.Tensor 'ExpandDims_1:0' shape=(None, 1) dtype=string>, 'Opportunity_Type': <tf.Tensor 'ExpandDims_9:0' shape=(None, 1) dtype=string>, 'Quote_Type': <tf.Tensor 'ExpandDims_11:0' shape=(None, 1) dtype=string>, 'Delivery_Terms': <tf.Tensor 'ExpandDims_6:0' shape=(None, 1) dtype=string>, 'Brand': <tf.Tensor 'ExpandDims_2:0' shape=(None, 1) dtype=string>, 'ASP_converted': <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=float64>, 'TRF': <tf.Tensor 'ExpandDims_15:0' shape=(None, 1) dtype=float64>, 'Total_Taxable_Amount': <tf.Tensor 'ExpandDims_16:0' shape=(None, 1) dtype=float64>, 'Delta_Time': <tf.Tensor 'ExpandDims_7:0' shape=(None, 1) dtype=float64>, 'Product_Amount': <tf.Tensor 'ExpandDims_10:0' shape=(None, 1) dtype=float64>, 'Same_Owner': <tf.Tensor 'ExpandDims_13:0' shape=(None, 1) dtype=string>, 'Delivery_Approved': <tf.Tensor 'ExpandDims_5:0' shape=(None, 1) dtype=int64>, 'Bureaucratic_Code_Approved': <tf.Tensor 'ExpandDims_4:0' shape=(None, 1) dtype=int64>}
Consider rewriting this model with the Functional API.
172/172 [==============================] - 3s 5ms/step - loss: 0.7230 - accuracy: 0.4757
Epoch 2/60
172/172 [==============================] - 1s 5ms/step - loss: 0.5869 - accuracy: 0.7189
Epoch 3/60
172/172 [==============================] - 1s 5ms/step - loss: 0.5080 - accuracy: 0.7997
Epoch 4/60
172/172 [==============================] - 1s 5ms/step - loss: 0.4540 - accuracy: 0.8461
Epoch 5/60
172/172 [==============================] - 1s 5ms/step - loss: 0.4157 - accuracy: 0.8744
Epoch 6/60
172/172 [==============================] - 1s 5ms/step - loss: 0.3792 - accuracy: 0.8918
Epoch 7/60
172/172 [==============================] - 1s 6ms/step - loss: 0.3464 - accuracy: 0.9107
Epoch 8/60
172/172 [==============================] - 1s 5ms/step - loss: 0.3229 - accuracy: 0.9203
Epoch 9/60
172/172 [==============================] - 1s 5ms/step - loss: 0.2987 - accuracy: 0.9372
Epoch 10/60
172/172 [==============================] - 1s 6ms/step - loss: 0.2805 - accuracy: 0.9417
Epoch 11/60
172/172 [==============================] - 1s 6ms/step - loss: 0.2677 - accuracy: 0.9455
Epoch 12/60
172/172 [==============================] - 1s 6ms/step - loss: 0.2496 - accuracy: 0.9532
Epoch 13/60
172/172 [==============================] - 1s 6ms/step - loss: 0.2326 - accuracy: 0.9566
Epoch 14/60
172/172 [==============================] - 1s 6ms/step - loss: 0.2255 - accuracy: 0.9597
Epoch 15/60
172/172 [==============================] - 1s 6ms/step - loss: 0.2145 - accuracy: 0.9590
Epoch 16/60
172/172 [==============================] - 1s 5ms/step - loss: 0.2068 - accuracy: 0.9602
Epoch 17/60
172/172 [==============================] - 1s 5ms/step - loss: 0.2028 - accuracy: 0.9593
Epoch 18/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1950 - accuracy: 0.9600
Epoch 19/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1921 - accuracy: 0.9572
Epoch 20/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1836 - accuracy: 0.9603
Epoch 21/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1718 - accuracy: 0.9627
Epoch 22/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1799 - accuracy: 0.9582
Epoch 23/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1669 - accuracy: 0.9625
Epoch 24/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1664 - accuracy: 0.9621
Epoch 25/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1647 - accuracy: 0.9615
Epoch 26/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1670 - accuracy: 0.9587
Epoch 27/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1661 - accuracy: 0.9590
Epoch 28/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1633 - accuracy: 0.9590
Epoch 29/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1559 - accuracy: 0.9613
Epoch 30/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1513 - accuracy: 0.9630
Epoch 31/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1473 - accuracy: 0.9645
Epoch 32/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1559 - accuracy: 0.9594
Epoch 33/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1464 - accuracy: 0.9632
Epoch 34/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1506 - accuracy: 0.9605
Epoch 35/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1510 - accuracy: 0.9615
Epoch 36/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1510 - accuracy: 0.9613
Epoch 37/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1550 - accuracy: 0.9593
Epoch 38/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1508 - accuracy: 0.9610
Epoch 39/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1458 - accuracy: 0.9611
Epoch 40/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1493 - accuracy: 0.9591
Epoch 41/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1433 - accuracy: 0.9627
Epoch 42/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1421 - accuracy: 0.9623
Epoch 43/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1511 - accuracy: 0.9583
Epoch 44/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1439 - accuracy: 0.9622
Epoch 45/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1455 - accuracy: 0.9611
Epoch 46/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1505 - accuracy: 0.9593
Epoch 47/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1423 - accuracy: 0.9628
Epoch 48/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1461 - accuracy: 0.9612
Epoch 49/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1420 - accuracy: 0.9625
Epoch 50/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1417 - accuracy: 0.9623
Epoch 51/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1390 - accuracy: 0.9624
Epoch 52/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1466 - accuracy: 0.9606
Epoch 53/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1566 - accuracy: 0.9575
Epoch 54/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1478 - accuracy: 0.9604
Epoch 55/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1394 - accuracy: 0.9629
Epoch 56/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1501 - accuracy: 0.9596
Epoch 57/60
172/172 [==============================] - 1s 5ms/step - loss: 0.1430 - accuracy: 0.9623
Epoch 58/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1475 - accuracy: 0.9603
Epoch 59/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1510 - accuracy: 0.9587
Epoch 60/60
172/172 [==============================] - 1s 6ms/step - loss: 0.1483 - accuracy: 0.9594
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_features (DenseFeature multiple                  0
_________________________________________________________________
dense (Dense)                multiple                  123
=================================================================
Total params: 123
Trainable params: 123
Non-trainable params: 0
_________________________________________________________________

Evaluamos el modelo

In [10]:
model.evaluate(ds_test)

WARNING:tensorflow:Layers in a Sequential model should only have a single input tensor, but we receive a <class 'dict'> input: {'Region': <tf.Tensor 'ExpandDims_12:0' shape=(None, 1) dtype=string>, 'Bureaucratic_Code': <tf.Tensor 'ExpandDims_3:0' shape=(None, 1) dtype=string>, 'Source': <tf.Tensor 'ExpandDims_14:0' shape=(None, 1) dtype=string>, 'Has_Contract_Number': <tf.Tensor 'ExpandDims_8:0' shape=(None, 1) dtype=string>, 'Account_Type': <tf.Tensor 'ExpandDims_1:0' shape=(None, 1) dtype=string>, 'Opportunity_Type': <tf.Tensor 'ExpandDims_9:0' shape=(None, 1) dtype=string>, 'Quote_Type': <tf.Tensor 'ExpandDims_11:0' shape=(None, 1) dtype=string>, 'Delivery_Terms': <tf.Tensor 'ExpandDims_6:0' shape=(None, 1) dtype=string>, 'Brand': <tf.Tensor 'ExpandDims_2:0' shape=(None, 1) dtype=string>, 'ASP_converted': <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=float64>, 'TRF': <tf.Tensor 'ExpandDims_15:0' shape=(None, 1) dtype=float64>, 'Total_Taxable_Amount': <tf.Tensor 'ExpandDims_16:0' shape=(None, 1) dtype=float64>, 'Delta_Time': <tf.Tensor 'ExpandDims_7:0' shape=(None, 1) dtype=float64>, 'Product_Amount': <tf.Tensor 'ExpandDims_10:0' shape=(None, 1) dtype=float64>, 'Same_Owner': <tf.Tensor 'ExpandDims_13:0' shape=(None, 1) dtype=string>, 'Delivery_Approved': <tf.Tensor 'ExpandDims_5:0' shape=(None, 1) dtype=int64>, 'Bureaucratic_Code_Approved': <tf.Tensor 'ExpandDims_4:0' shape=(None, 1) dtype=int64>}
Consider rewriting this model with the Functional API.
4/4 [==============================] - 0s 6ms/step - loss: 0.1016 - accuracy: 0.9800

[0.10163770616054535, 0.9800000190734863]

Escribimos las predicciones

In [11]:

frio_test_df = pd.read_csv('/content/Test_TP2_Datos_2020-2C.csv')
frio_test_df['Stage'] = 'Closed Won' #Esto esta solo para que funque todo, no lo uso. No se bien como armarlo sin los labels de Stage. TODO: Averiguar como es!
aux_df = frio_test_df[['Opportunity_ID']] #Esta columna la vuela el preprocesado sino
frio_test_df = preprocess_dataframe(frio_test_df)
frio_test_ds = df_to_dataset(frio_test_df, shuffle=False, batch_size=56)
predictions = model.predict(frio_test_ds)

aux_df.drop_duplicates(subset='Opportunity_ID', inplace=True) #Lo hacia el preprocesado pero es verdad que lo copie antes a este xd, perdon Agus, paja de dejarlo lindo.
aux_df['Target'] = predictions

#aux_df['Target'] = aux_df.groupby(by='Opportunity_ID').transform(lambda x: x.mean())
#aux_df.drop_duplicates(subset='Opportunity_ID', inplace=True)

aux_df.to_csv('prediccionesFrioFrio.csv', index=False)
'''
df = pd.read_csv('/content/Train_TP2_Datos_2020-2C.csv')
df = df[(df['Stage'] == 'Closed Won') | (df['Stage'] == 'Closed Lost')]
df = df[df['Opportunity_ID'] != 9773]
df = df[['Opportunity_ID']]
df.drop_duplicates(subset='Opportunity_ID', inplace=True)
np.random.seed(1)
drop_indices = np.random.choice(df.index, test_lines, replace=False)
df.drop(drop_indices, inplace=True)
predictions = model.predict(ds)
df['Target'] = predictions
df.to_csv('prediccionesFrioFrio.csv', index=False)
'''

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

WARNING:tensorflow:Layers in a Sequential model should only have a single input tensor, but we receive a <class 'dict'> input: {'Region': <tf.Tensor 'ExpandDims_12:0' shape=(None, 1) dtype=string>, 'Bureaucratic_Code': <tf.Tensor 'ExpandDims_3:0' shape=(None, 1) dtype=string>, 'Source': <tf.Tensor 'ExpandDims_14:0' shape=(None, 1) dtype=string>, 'Has_Contract_Number': <tf.Tensor 'ExpandDims_8:0' shape=(None, 1) dtype=string>, 'Account_Type': <tf.Tensor 'ExpandDims_1:0' shape=(None, 1) dtype=string>, 'Opportunity_Type': <tf.Tensor 'ExpandDims_9:0' shape=(None, 1) dtype=string>, 'Quote_Type': <tf.Tensor 'ExpandDims_11:0' shape=(None, 1) dtype=string>, 'Delivery_Terms': <tf.Tensor 'ExpandDims_6:0' shape=(None, 1) dtype=string>, 'Brand': <tf.Tensor 'ExpandDims_2:0' shape=(None, 1) dtype=string>, 'ASP_converted': <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=float64>, 'TRF': <tf.Tensor 'ExpandDims_15:0' shape=(None, 1) dtype=float64>, 'Total_Taxable_Amount': <tf.Tensor 'ExpandDims_16:0' shape=(None, 1) dtype=float64>, 'Delta_Time': <tf.Tensor 'ExpandDims_7:0' shape=(None, 1) dtype=float64>, 'Product_Amount': <tf.Tensor 'ExpandDims_10:0' shape=(None, 1) dtype=float64>, 'Same_Owner': <tf.Tensor 'ExpandDims_13:0' shape=(None, 1) dtype=string>, 'Delivery_Approved': <tf.Tensor 'ExpandDims_5:0' shape=(None, 1) dtype=int64>, 'Bureaucratic_Code_Approved': <tf.Tensor 'ExpandDims_4:0' shape=(None, 1) dtype=int64>}
Consider rewriting this model with the Functional API.

"\ndf = pd.read_csv('/content/Train_TP2_Datos_2020-2C.csv')\ndf = df[(df['Stage'] == 'Closed Won') | (df['Stage'] == 'Closed Lost')]\ndf = df[df['Opportunity_ID'] != 9773]\ndf = df[['Opportunity_ID']]\ndf.drop_duplicates(subset='Opportunity_ID', inplace=True)\nnp.random.seed(1)\ndrop_indices = np.random.choice(df.index, test_lines, replace=False)\ndf.drop(drop_indices, inplace=True)\npredictions = model.predict(ds)\ndf['Target'] = predictions\ndf.to_csv('prediccionesFrioFrio.csv', index=False)\n"